---
- hosts: 127.0.0.1
  vars:
    - virtualenv: /home/sameedo/.virtualenvs/portal
    - git_repo: ssh://git@github.com:doroob-edx/portal.git
    - git_dest: /home/sameedo/portal
    - requirements_path: /home/sameedo/portal/requirements.txt
    - app_path: /home/sameedo/portal
    - settings_path: molPortal.settings_dev
  remote_user: sameedo
  tasks:
    - name: test server connection
      ping:
      remote_user: sameedo
    - name: pull latest code
      git: repo={{ git_repo }}
        dest={{ git_dest }}
        accept_hostkey=True
        update=False
    - name: Install packages required by the Django app inside virtualenv
      pip: virtualenv={{ virtualenv }} requirements={{ requirements_path }}
    - name: Run the Django syncdb command
      django_manage:
        command: syncdb
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv }}"
        settings: "{{ settings_path }}"
    - name: Run Django South migrations
      django_manage:
        command: migrate
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv }}"
        settings: "{{ settings_path }}"
    - name: Run Django collectstatic
      django_manage:
        command: collectstatic
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv }}"
        settings: "{{ settings_path }}"
#    - name: Restart Supervisor
#      supervisorctl: name=doroob state=restarted